import type { FormEvent } from "react";
import type { CatalogItem, Connector, NetworkNode, Splice, WireEndpoint, WireMaterial } from "../../../core/entities";
import type { DirectionalSpliceSide } from "../../../core/directionalSplice";
import type { DeleteDependencySummaryCategory } from "../../../store/deleteImpact";
import type { SplicePortMode } from "../../../core/splicePortMode";
import type { ModelingBatchSelectionScope } from "../../lib/modelingBatchDelete";
import type { WireEndpointSlotHint } from "../../hooks/wireEndpointFormHelpers";
import type { ConnectorFusePairRatingDrafts } from "../../hooks/connectorFusePairRatings";

export interface ModelingFormsColumnProps {
  catalogItems: CatalogItem[];
  openCatalogSubScreen: () => void;
  onSelectCatalogItem: (catalogItemId: CatalogItem["id"]) => void;
  isConnectorSubScreen: boolean;
  connectorFormMode: "idle" | "create" | "edit";
  connectorEditAfterCreate: boolean;
  openCreateConnectorForm: () => void;
  handleConnectorSubmit: (event: FormEvent<HTMLFormElement>) => void;
  connectorName: string;
  setConnectorName: (value: string) => void;
  connectorTechnicalId: string;
  setConnectorTechnicalId: (value: string) => void;
  connectorCatalogItemId: string;
  setConnectorCatalogItemId: (value: string) => void;
  connectorManufacturerReference: string;
  setConnectorManufacturerReference: (value: string) => void;
  connectorIsMainHarnessConnector: boolean;
  setConnectorIsMainHarnessConnector: (value: boolean) => void;
  connectorApplyCatalogPlugs: boolean;
  setConnectorApplyCatalogPlugs: (value: boolean) => void;
  connectorApplyCatalogSeals: boolean;
  setConnectorApplyCatalogSeals: (value: boolean) => void;
  connectorTerminalOverridesText: string;
  setConnectorTerminalOverridesText: (value: string) => void;
  connectorFusePairRatings: ConnectorFusePairRatingDrafts;
  setConnectorFusePairRatings: (value: ConnectorFusePairRatingDrafts) => void;
  connectorAutoCreateLinkedNode: boolean;
  setConnectorAutoCreateLinkedNode: (value: boolean) => void;
  connectorTechnicalIdAlreadyUsed: boolean;
  cavityCount: string;
  setCavityCount: (value: string) => void;
  cancelConnectorEdit: () => void;
  connectorFormError: string | null;
  isSpliceSubScreen: boolean;
  spliceFormMode: "idle" | "create" | "edit";
  spliceEditAfterCreate: boolean;
  openCreateSpliceForm: () => void;
  handleSpliceSubmit: (event: FormEvent<HTMLFormElement>) => void;
  handleConvertSpliceToDirectional: () => void;
  handleRerouteSpliceConnectedWires: () => void;
  handleSuggestOptimizedSplicePlacement: () => void;
  spliceName: string;
  setSpliceName: (value: string) => void;
  spliceTechnicalId: string;
  setSpliceTechnicalId: (value: string) => void;
  spliceCatalogItemId: string;
  setSpliceCatalogItemId: (value: string) => void;
  splicePortMode: SplicePortMode;
  setSplicePortMode: (value: SplicePortMode) => void;
  spliceSideInverted: boolean;
  setSpliceSideInverted: (value: boolean) => void;
  spliceManufacturerReference: string;
  setSpliceManufacturerReference: (value: string) => void;
  spliceAutoCreateLinkedNode: boolean;
  setSpliceAutoCreateLinkedNode: (value: boolean) => void;
  spliceTechnicalIdAlreadyUsed: boolean;
  portCount: string;
  setPortCount: (value: string) => void;
  spliceFormInfo: string | null;
  cancelSpliceEdit: () => void;
  spliceFormError: string | null;
  isNodeSubScreen: boolean;
  nodeFormMode: "idle" | "create" | "edit";
  nodeEditAfterCreate: boolean;
  openCreateNodeForm: () => void;
  handleNodeSubmit: (event: FormEvent<HTMLFormElement>) => void;
  nodeIdInput: string;
  setNodeIdInput: (value: string) => void;
  pendingNewNodePosition: { x: number; y: number } | null;
  nodeKind: NetworkNode["kind"];
  setNodeKind: (value: NetworkNode["kind"]) => void;
  nodeLabel: string;
  setNodeLabel: (value: string) => void;
  connectors: Connector[];
  nodeConnectorId: string;
  setNodeConnectorId: (value: string) => void;
  splices: Splice[];
  nodeSpliceId: string;
  setNodeSpliceId: (value: string) => void;
  cancelNodeEdit: () => void;
  nodeFormError: string | null;
  isSegmentSubScreen: boolean;
  segmentFormMode: "idle" | "create" | "edit";
  segmentEditAfterCreate: boolean;
  openCreateSegmentForm: () => void;
  handleSegmentSubmit: (event: FormEvent<HTMLFormElement>) => void;
  handleSwapSegmentNodes: () => void;
  segmentIdInput: string;
  setSegmentIdInput: (value: string) => void;
  nodes: NetworkNode[];
  describeNode: (node: NetworkNode) => string;
  segmentNodeA: string;
  setSegmentNodeA: (value: string) => void;
  segmentNodeB: string;
  setSegmentNodeB: (value: string) => void;
  segmentLengthMm: string;
  setSegmentLengthMm: (value: string) => void;
  segmentSubNetworkTag: string;
  setSegmentSubNetworkTag: (value: string) => void;
  cancelSegmentEdit: () => void;
  segmentFormError: string | null;
  isWireSubScreen: boolean;
  wireFormMode: "idle" | "create" | "edit";
  wireEditAfterCreate: boolean;
  openCreateWireForm: () => void;
  handleWireSubmit: (event: FormEvent<HTMLFormElement>) => void;
  handleSwapWireEndpoints: () => void;
  wireName: string;
  setWireName: (value: string) => void;
  wireTechnicalId: string;
  setWireTechnicalId: (value: string) => void;
  wireTwistGroupLabel: string;
  setWireTwistGroupLabel: (value: string) => void;
  wireFunctionalDomainTag: string;
  setWireFunctionalDomainTag: (value: string) => void;
  wireSectionMm2: string;
  setWireSectionMm2: (value: string) => void;
  wireCurrentA: string;
  setWireCurrentA: (value: string) => void;
  wireMaterial: WireMaterial;
  setWireMaterial: (value: WireMaterial) => void;
  recommendedWireSectionMm2: number | null;
  handleApplyRecommendedWireSection: () => void;
  wireColorMode: "none" | "catalog" | "free";
  setWireColorMode: (value: "none" | "catalog" | "free") => void;
  wirePrimaryColorId: string;
  setWirePrimaryColorId: (value: string) => void;
  wireSecondaryColorId: string;
  setWireSecondaryColorId: (value: string) => void;
  wireFreeColorLabel: string;
  setWireFreeColorLabel: (value: string) => void;
  wireFuseEnabled: boolean;
  setWireFuseEnabled: (value: boolean) => void;
  wireFuseCatalogItemId: string;
  setWireFuseCatalogItemId: (value: string) => void;
  wireTechnicalIdAlreadyUsed: boolean;
  wireEndpointAConnectionReference: string;
  setWireEndpointAConnectionReference: (value: string) => void;
  wireEndpointAConnectionName: string;
  setWireEndpointAConnectionName: (value: string) => void;
  wireEndpointASealReference: string;
  setWireEndpointASealReference: (value: string) => void;
  wireEndpointASealName: string;
  setWireEndpointASealName: (value: string) => void;
  wireEndpointAKind: WireEndpoint["kind"];
  setWireEndpointAKind: (value: WireEndpoint["kind"]) => void;
  wireEndpointAConnectorId: string;
  setWireEndpointAConnectorId: (value: string) => void;
  wireEndpointACavityIndex: string;
  setWireEndpointACavityIndex: (value: string) => void;
  wireEndpointASpliceId: string;
  setWireEndpointASpliceId: (value: string) => void;
  wireEndpointAPortIndex: string;
  setWireEndpointAPortIndex: (value: string) => void;
  wireEndpointASpliceSideOverride: DirectionalSpliceSide | "auto";
  setWireEndpointASpliceSideOverride: (value: DirectionalSpliceSide | "auto") => void;
  wireEndpointASpliceSideLocked: boolean;
  setWireEndpointASpliceSideLocked: (value: boolean) => void;
  wireEndpointASlotHint: WireEndpointSlotHint | null;
  wireEndpointBConnectionReference: string;
  setWireEndpointBConnectionReference: (value: string) => void;
  wireEndpointBConnectionName: string;
  setWireEndpointBConnectionName: (value: string) => void;
  wireEndpointBSealReference: string;
  setWireEndpointBSealReference: (value: string) => void;
  wireEndpointBSealName: string;
  setWireEndpointBSealName: (value: string) => void;
  wireEndpointBKind: WireEndpoint["kind"];
  setWireEndpointBKind: (value: WireEndpoint["kind"]) => void;
  wireEndpointBConnectorId: string;
  setWireEndpointBConnectorId: (value: string) => void;
  wireEndpointBCavityIndex: string;
  setWireEndpointBCavityIndex: (value: string) => void;
  wireEndpointBSpliceId: string;
  setWireEndpointBSpliceId: (value: string) => void;
  wireEndpointBPortIndex: string;
  setWireEndpointBPortIndex: (value: string) => void;
  wireEndpointBSpliceSideOverride: DirectionalSpliceSide | "auto";
  setWireEndpointBSpliceSideOverride: (value: DirectionalSpliceSide | "auto") => void;
  wireEndpointBSpliceSideLocked: boolean;
  setWireEndpointBSpliceSideLocked: (value: boolean) => void;
  wireEndpointBSlotHint: WireEndpointSlotHint | null;
  cancelWireEdit: () => void;
  wireFormError: string | null;
  modelingBatchSelection:
    | {
        scope: ModelingBatchSelectionScope;
        selectedCount: number;
        directCount: number;
        cascadeCount: number;
        blockedCount: number;
        summaryCategories: DeleteDependencySummaryCategory[];
        summaryNote?: string;
        onDeleteSelected: () => void;
        onCancelBatchMode: () => void;
      }
    | null;
}
