import type { FormEvent } from "react";
import type { CatalogItem, Connector, NetworkNode, Splice, WireEndpoint } from "../../../core/entities";
import type { WireEndpointSlotHint } from "../../hooks/useWireHandlers";

export interface ModelingFormsColumnProps {
  catalogItems: CatalogItem[];
  openCatalogSubScreen: () => void;
  isConnectorSubScreen: boolean;
  connectorFormMode: "idle" | "create" | "edit";
  openCreateConnectorForm: () => void;
  handleConnectorSubmit: (event: FormEvent<HTMLFormElement>) => void;
  connectorName: string;
  setConnectorName: (value: string) => void;
  connectorTechnicalId: string;
  setConnectorTechnicalId: (value: string) => void;
  connectorCatalogItemId: string;
  setConnectorCatalogItemId: (value: string) => void;
  connectorManufacturerReference: string;
  setConnectorManufacturerReference: (value: string) => void;
  connectorAutoCreateLinkedNode: boolean;
  setConnectorAutoCreateLinkedNode: (value: boolean) => void;
  connectorTechnicalIdAlreadyUsed: boolean;
  cavityCount: string;
  setCavityCount: (value: string) => void;
  cancelConnectorEdit: () => void;
  connectorFormError: string | null;
  isSpliceSubScreen: boolean;
  spliceFormMode: "idle" | "create" | "edit";
  openCreateSpliceForm: () => void;
  handleSpliceSubmit: (event: FormEvent<HTMLFormElement>) => void;
  spliceName: string;
  setSpliceName: (value: string) => void;
  spliceTechnicalId: string;
  setSpliceTechnicalId: (value: string) => void;
  spliceCatalogItemId: string;
  setSpliceCatalogItemId: (value: string) => void;
  spliceManufacturerReference: string;
  setSpliceManufacturerReference: (value: string) => void;
  spliceAutoCreateLinkedNode: boolean;
  setSpliceAutoCreateLinkedNode: (value: boolean) => void;
  spliceTechnicalIdAlreadyUsed: boolean;
  portCount: string;
  setPortCount: (value: string) => void;
  cancelSpliceEdit: () => void;
  spliceFormError: string | null;
  isNodeSubScreen: boolean;
  nodeFormMode: "idle" | "create" | "edit";
  openCreateNodeForm: () => void;
  handleNodeSubmit: (event: FormEvent<HTMLFormElement>) => void;
  nodeIdInput: string;
  setNodeIdInput: (value: string) => void;
  pendingNewNodePosition: { x: number; y: number } | null;
  nodeKind: NetworkNode["kind"];
  setNodeKind: (value: NetworkNode["kind"]) => void;
  nodeLabel: string;
  setNodeLabel: (value: string) => void;
  connectors: Connector[];
  nodeConnectorId: string;
  setNodeConnectorId: (value: string) => void;
  splices: Splice[];
  nodeSpliceId: string;
  setNodeSpliceId: (value: string) => void;
  cancelNodeEdit: () => void;
  nodeFormError: string | null;
  isSegmentSubScreen: boolean;
  segmentFormMode: "idle" | "create" | "edit";
  openCreateSegmentForm: () => void;
  handleSegmentSubmit: (event: FormEvent<HTMLFormElement>) => void;
  handleSwapSegmentNodes: () => void;
  segmentIdInput: string;
  setSegmentIdInput: (value: string) => void;
  nodes: NetworkNode[];
  describeNode: (node: NetworkNode) => string;
  segmentNodeA: string;
  setSegmentNodeA: (value: string) => void;
  segmentNodeB: string;
  setSegmentNodeB: (value: string) => void;
  segmentLengthMm: string;
  setSegmentLengthMm: (value: string) => void;
  segmentSubNetworkTag: string;
  setSegmentSubNetworkTag: (value: string) => void;
  cancelSegmentEdit: () => void;
  segmentFormError: string | null;
  isWireSubScreen: boolean;
  wireFormMode: "idle" | "create" | "edit";
  openCreateWireForm: () => void;
  handleWireSubmit: (event: FormEvent<HTMLFormElement>) => void;
  handleSwapWireEndpoints: () => void;
  wireName: string;
  setWireName: (value: string) => void;
  wireTechnicalId: string;
  setWireTechnicalId: (value: string) => void;
  wireSectionMm2: string;
  setWireSectionMm2: (value: string) => void;
  wireColorMode: "none" | "catalog" | "free";
  setWireColorMode: (value: "none" | "catalog" | "free") => void;
  wirePrimaryColorId: string;
  setWirePrimaryColorId: (value: string) => void;
  wireSecondaryColorId: string;
  setWireSecondaryColorId: (value: string) => void;
  wireFreeColorLabel: string;
  setWireFreeColorLabel: (value: string) => void;
  wireFuseEnabled: boolean;
  setWireFuseEnabled: (value: boolean) => void;
  wireFuseCatalogItemId: string;
  setWireFuseCatalogItemId: (value: string) => void;
  wireTechnicalIdAlreadyUsed: boolean;
  wireEndpointAConnectionReference: string;
  setWireEndpointAConnectionReference: (value: string) => void;
  wireEndpointASealReference: string;
  setWireEndpointASealReference: (value: string) => void;
  wireEndpointAKind: WireEndpoint["kind"];
  setWireEndpointAKind: (value: WireEndpoint["kind"]) => void;
  wireEndpointAConnectorId: string;
  setWireEndpointAConnectorId: (value: string) => void;
  wireEndpointACavityIndex: string;
  setWireEndpointACavityIndex: (value: string) => void;
  wireEndpointASpliceId: string;
  setWireEndpointASpliceId: (value: string) => void;
  wireEndpointAPortIndex: string;
  setWireEndpointAPortIndex: (value: string) => void;
  wireEndpointASlotHint: WireEndpointSlotHint | null;
  wireEndpointBConnectionReference: string;
  setWireEndpointBConnectionReference: (value: string) => void;
  wireEndpointBSealReference: string;
  setWireEndpointBSealReference: (value: string) => void;
  wireEndpointBKind: WireEndpoint["kind"];
  setWireEndpointBKind: (value: WireEndpoint["kind"]) => void;
  wireEndpointBConnectorId: string;
  setWireEndpointBConnectorId: (value: string) => void;
  wireEndpointBCavityIndex: string;
  setWireEndpointBCavityIndex: (value: string) => void;
  wireEndpointBSpliceId: string;
  setWireEndpointBSpliceId: (value: string) => void;
  wireEndpointBPortIndex: string;
  setWireEndpointBPortIndex: (value: string) => void;
  wireEndpointBSlotHint: WireEndpointSlotHint | null;
  cancelWireEdit: () => void;
  wireFormError: string | null;
}
